.TH ccutter "1" "Novembre 2018" "Commandes utilisateur"
.SH NOM
ccutter \- éditeur de musique SID
.SH SYNOPSIS
.B ccutter
[\fI\,OPTION\/\fR]... [\fI\,FICHIER\/\fR]
.SH DESCRIPTION
CheeseCutter (C) 2009\-17 Abaddon
Publié sous GNU GPL.
.SH OPTIONS
.TP
\fB\-b\fR [valeur]
Définir la taille du tampon de lecture (déf=2048)
.TP
\fB\-f\fR
Démarrer en mode plein écran
.TP
\fB\-nofp\fR
Ne pas utiliser l'émulation resid\-fp
.TP
\fB\-fpr\fR [x]
Spécifie le préréglage de filtre. x = 0..16 pour 6581 et 0..1 pour 8580
.TP
\fB\-i\fR
Désactive l'interpolation resid (utilise le mode rapide à la place)
.TP
\fB\-m\fR [0|1]
Spécifie le modèle SID pour reSID (6581/8580) (déf=0)
.TP
\fB\-n\fR
Active le mode NTSC
.TP
\fB\-r\fR [value]
Paramètre la fréquence de lecture (déf=48000)
.TP
\fB\-y\fR
Utiliser la superposition vidéo YUV
.SH AUTEUR
Michel Vergnaud \- Copyright 2015\-2016.
.PP
Cette page de manuel a été traduite par Olivier Humbert "trebmuh" <trebmuh@tuxfamily.org> le 24 avril 2019 pour le projet LibraZiK et peut être utilisée par tout un chacun.
